config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users



  root 'users#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many :suites
end

app/models/role.rb
class Role < ApplicationRecord
    belongs_to :user
end

app/models/suite.rb
class suite < ApplicationRecord
    belongs_to :hotel
end

app/models/user.rb
class User < ApplicationRecord
    has_many :roles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
private
def current_user
  User.where(id: session[:user_id]).first
end
helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
      user = User.where(email: params[:email], password_digest: params[:password]).first
      if user
        session[:user_id] = user.id
        redirect_to root_url, notice: 'Vous êtes connectés ! '
      else
        render :new
      end
    end
    def destroy
      session[:user_id] = nil
      redirect_to root_url, notice: 'Vous êtes déconnecter !'
    end
  end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @role = @user.roles
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password_digest, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :adress, style: "display: block" %>
    <%= form.text_field :adress %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p>
    <strong>Nom:</strong>
    <%= hotel.name %>
  </p>

  <p>
    <strong>Adresse:</strong>
    <%= hotel.adress %>
  </p>

  <p>
    <strong>City :</strong>
    <%= hotel.city %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= hotel.description %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= hotel.user_id %>
  </p>

</div>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hotels</h1>

<div id="hotels">
  <% @hotels.each do |hotel| %>
    <%= render hotel %>
    <p>
      <%= link_to "Show this hotel", hotel %>
    </p>
  <% end %>
</div>

<%= link_to "New hotel", new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hotel %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel) %> |
  <%= link_to "Back to hotels", hotels_path %>

  <%= button_to "Destroy this hotel", @hotel, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hypnos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
   <div id="user_header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Hypnos</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Menu</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Menu</a>
            </li>

            <div class="dropleft" style="display: flex;position: relative;left: 900px;">
            <% if !current_user %>
              <li class="nav-item">
                <%= link_to "S'inscrire", signup_path, class: "btn btn-primary" %>&nbsp;
              </li>
              <li class="nav-item">
                <%= link_to "Se connecter", login_path, class: "btn btn-secondary" %>
              </li>
                       
            <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profil (<%= current_user.first_name %> <%= current_user.last_name %> )
              </a>
             
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="#">
                    <%= link_to "Se déconnecter", logout_path,class: "btn btn-primary" %>
                </a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
              <% end %>
               </div> 
            </li>
          </ul>
        </div>
      </div>
    </nav>
    </div>

    <div class="container">
      <%= yield  %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

<% if !current_user %>
    <%= form.text_field :role_id,value: 3,hidden: true %>
<% else %>
  <div>
    <%= form.label :role_id, style: "display: block" %>
    <%= form.text_field :role_id,value: 2 %>
  </div>
<% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role_id %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>